import Head from 'next/head'

const Titulo = () => {
    return (
        <Head>
            <title>Marvel</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/iconLee.png" />
        </Head>
    )
}
export default Titulo